### ISSUE TITLE
btrfs compression

### ISSUE THREAD

**Issue by 2ZZ** [patschbo/BaNG#1]
Hi patschbo,

Do you recommend enabling the compression option on the btrfs mount point or are there reasons why this shouldn't be done?

Thanks

**Comment by patschbo** [comment]
Hi 2ZZ,

i have compression enabled and i don`t have any troubles. I use lzo and zstd for compression.
But i use the latest stable Linux-Kernel , currently 4.15.2.

Regards patschbo

**Comment by 2ZZ** [comment]
thanks
